### ISSUE TITLE
Support for Visual Studio 2019 Dark theme

### ISSUE THREAD

**Issue by urielzen** [ghaschel/vscode-angular-html#52]
When installing the `C#` extension, we get access to two additional themes. One of them being `Visual Studio 2019 Dark` theme.

![image](https://user-images.githubusercontent.com/7947179/186975567-7b3396b1-4fab-4f04-b002-4652b2c53094.png)

This theme has js/ts file colors very familiar to me as a Visual Studio user.

However it does not seem to play well with vscode-angular-html as some colors are missing in templates.

![image](https://user-images.githubusercontent.com/7947179/186975999-ecfbc78f-6e7f-4c17-8921-a27b076de8c6.png)

I would like to avoid installing `dark-plus-syntax` because it does not have the js/ts file colors that `Visual Studio 2019 Dark` has.

Not a deal breaker, but is there any chance `vscode-angular-html` could close the gap in missing colors when used with `Visual Studio 2019 Dark`?

Thank you so much for such a great extension.

**Comment by ghaschel** [comment]
Hey, thanks for reporting it!

Unfortunately this is working "correctly" as when I started this plugin I didn't really knew what I was doing. I made it in such a way it basically relies on vscode-syntax-plus to achieve this highlighting.

There is a complete rewrite of this package upcoming which would allow both semantic highlighting and color customizations If I'm able to do all I want.

But unfortunately I have no ETA at the moment. But Either way, I'll let this issue open and I'll inform you here too whenever this is done

**Comment by ghaschel** [comment]
I'm having a ton of progress in this. 

I was able to create a syntax highlighting that follows the correct HTML scope naming, also, adding a few extra scopes, in which one can add visual differentiation just like I was doing before, but allowing color customization.

I believe the highlight itself should be done by next week. But I'll try to add a settings page in which users can set their own colors to these elements. I say try, because I'm not really aware of the vscode plugin settings api and their limitations... But it is in the plans, and in the making

And also, I will document everything so that if someone wants to support this plugin via themes, it could be done the correct way.

**Comment by urielzen** [comment]
We don't deserve people like you... I really appreciate it. Please make sure you rest enough and don't stress about this task.

**Comment by ghaschel** [comment]
This was added in version 2.0.0

It should match the default HTML.derivative scope, or close to it, and you can then customize all the extra-matched scopes with the color you want.

Feel free to open another issue if you need to.
😄
