### ISSUE TITLE
feat: Allow to customize color of custom tags (components)

### ISSUE THREAD

**Issue by Daranix** [ghaschel/vscode-angular-html#63]
**Is your feature request related to a problem? Please describe.**
With the latest version of the extension, the custom html tags which are not from angular/angular material shows with color white

**Describe the solution you'd like**
I would like to be able to customize this tags with different a different color

**Additional context**

Here's a screenshot showing the current behaviour

![image](https://user-images.githubusercontent.com/13921690/195983233-cb5bac45-8e89-4b3f-aa2d-75217144ca25.png)

Thanks for this great extension!

**Comment by NikolaKrstic94** [comment]
For me almost all the predefined default colors are gone after the latest update. Can anyone help me revert it to how it was prior to yesterday's update? Not sure where to look.  Sorry for hijacking the thread.

**Comment by niklasxulls** [comment]
> For me almost all the predefined default colors are gone after the latest update. Can anyone help me revert it to how it was prior to yesterday's update? Not sure where to look. Sorry for hijacking the thread.

I have the same problem, I just rolled back the version in order to make it work again: https://stackoverflow.com/questions/42626065/vs-code-how-to-rollback-extension-install-specific-extension-version

**Comment by ghaschel** [comment]
@NikolaKrstic94 @niklasxulls That is because now, you can use a different theme and tweak the extra-matched characters to your liking 
via extension settings. But if you want to have the same colors as before, please, open the command pallet and run the command `vscode-angular-html: Set Legacy Colors`
Let me know if that solves your issues.

@Daranix I'll take a look on that first thing on Monday. But prior to that, can you confirm me if something like `<custom-element>` shows up correctly to you, please?

**Comment by niklasxulls** [comment]
> @NikolaKrstic94 @niklasxulls That is because now, you can use a different theme and tweak the extra-matched characters to your liking via extension settings. But if you want to have the same colors as before, please, open the command pallet and run the command `vscode-angular-html: Set Legacy Colors` Let me know if that solves your issues.
> 
> @Daranix I'll take a look on that first thing on Monday. But prior to that, can you confirm me if something like `<custom-element>` shows up correctly to you, please?

I've already tried that, before rolling back - also reloading, dis/enabling, restarting vscode, etc. didn't help

**Comment by NikolaKrstic94** [comment]
@niklasxulls  It partially works, however, it completely overrides my Monokai++ theme which is not optimal at all. Also the colors themselves are not the same as they were on 1.8 as well, things like "class"' was green but now it's cyan.  I've reverted to version 1.8 for the time being.  

Edit: With `vscode-angular-html: Set Legacy Colors` command on the latest 2.0.2 version: 
![command  Set Legacy Colors](https://user-images.githubusercontent.com/25144458/196006644-545440a9-13a5-420d-9834-93cd165d13e1.png)

Default settings latest 2.0.2 version:
![default on latest version](https://user-images.githubusercontent.com/25144458/196006814-11291a48-71bb-46a7-ad4c-b5086c3fd787.png)

1.8.4 default settings: 
![1 8 4 version default settings](https://user-images.githubusercontent.com/25144458/196006650-17e40b7c-2ccd-43be-86b3-050d34ad7f89.png)

**Comment by Daranix** [comment]
> @NikolaKrstic94 @niklasxulls That is because now, you can use a different theme and tweak the extra-matched characters to your liking via extension settings. But if you want to have the same colors as before, please, open the command pallet and run the command `vscode-angular-html: Set Legacy Colors` Let me know if that solves your issues.
> 
> @Daranix I'll take a look on that first thing on Monday. But prior to that, can you confirm me if something like `<custom-element>` shows up correctly to you, please?

I tried a few additional things the conclusion I get is seems like only shows as white color when the tag starts with a single caracter and `-` like on `p-calendar` or on `a-hello`

![image](https://user-images.githubusercontent.com/13921690/196040347-8a798d22-6cff-4981-bf95-457dcdc37a10.png)

**Comment by sheamer** [comment]
I'm having the same issue with @Daranix I also lost all the highlighting in my primeng tags. Primeng tags start with single characters

<p-table>
<p-dropdown>
<p-toast>

**Comment by ghaschel** [comment]
@Daranix just to explain some things

When I first developed this extension I didn't know much how TextMate Grammars work. And I developed the extension to work properly with dark-syntax-plus theme. But turns out as I was randomly choosing scopes to apply to a specific match to turn make it the color I wanted, because I wanted it to as colorful as possible and wanted it to differentiate between as much things as possible. I was not being semantically correct, and thus causing the extension not to have the same effect in many other themes. What I done now is: 
- Applying correct scopes
- Applying an extra custom scope so that I can customize it via extension settings
- Allowing people to choose between the previous extra-color matching and the default one...

The legacy colors command works by applying the colors that were the dark-syntax-plus colors. But I believe I the way i should have gone is:
- Making the legacy colors command colors to be the default flavor, and it can be disabled, and instead of having dark-syntax-plus colors, it should instead get the colors from the current theme, and apply it as colors customizations.

I'll fix now the primeng tags and release a bugfix.

The legacy colors being acquired from the current theme' scopes is absolute next.

Please, for the legacy colors feature refer to [this issue](https://github.com/ghaschel/vscode-angular-html/issues/65)

**Comment by ghaschel** [comment]
Related to PrimeNG, [this](https://github.com/ghaschel/vscode-angular-html/issues/64#issuecomment-1281026635) is the list of components this bugfix will be covering.

Along with the fix for the scenario with `a-component` issue, these elements I listed in the issue, will be matched by default with the `custom-element` colors, with the `angular-material` color with `legacy colors` command, and may have their color changed via extension settings.

As I am going to fix the legacy colors bug, I wanted an input from you guys, that work with prime-ng. Do you prefer it to have a `custom-element` color or would you prefer it to have the `angular-material` structural tags color?

Let me know if you prefer the custom-element ones so that I can change it back.

**Comment by Daranix** [comment]
It would be great, if the elements of primeNG act the same as those of angular material :smile:

**Comment by ghaschel** [comment]
For those who are using dark-syntax-plus or even Dark+, this is working by using the legacy colors command.

@Daranix Can you please take a look at [this list](https://github.com/ghaschel/vscode-angular-html/issues/64#issuecomment-1281026635) and let me know if there's any missing primeNG elements that pop into your head?

**Comment by ghaschel** [comment]
Regarding the colors being acquired by the theme, there is no easy and clean way to get the *inherited* color by the scope, only the full scope, and it is not really granted.

For example:

In 1.8.4, the html attribute scope was `support.type.object.html-attribute`, which was being inherited by `support.type` in some themes, and in `support.type.object` in others. And In some themes this scope wasn't being applied any colors.

So, the best solution I could think of now, is:

I will list the most used VSCode themes, and support it manually one by one (using 1.8.4 as the original), and then, as a fallback, use the method I found to fetch the theme scope colors, and apply it in a very generic way, basing myself on the VSCode's Default Dark+.

I will add then an Issue template for theme support

**Comment by ghaschel** [comment]
So far:

Per popularity:
- [C/C++ Themes](https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools-themes)
- [One Dark Pro](https://marketplace.visualstudio.com/items?itemName=zhuangtongfa.Material-theme)
- [Github Theme](https://marketplace.visualstudio.com/items?itemName=GitHub.github-vscode-theme)
- [Dracula Official](https://marketplace.visualstudio.com/items?itemName=dracula-theme.theme-dracula)
- [Atom One Dark Theme](https://marketplace.visualstudio.com/items?itemName=akamud.vscode-theme-onedark)
- [Community Material Theme](https://marketplace.visualstudio.com/items?itemName=Equinusocio.vsc-community-material-theme)
- [Winter Is Coming Theme](https://marketplace.visualstudio.com/items?itemName=johnpapa.winteriscoming)
- [Monokai Pro](https://marketplace.visualstudio.com/items?itemName=monokai.theme-monokai-pro-vscode)
- [Night Owl](https://marketplace.visualstudio.com/items?itemName=sdras.night-owl)
- [Material Theme](https://marketplace.visualstudio.com/items?itemName=Equinusocio.vsc-material-theme)
- [Ayu](https://marketplace.visualstudio.com/items?itemName=teabyii.ayu)
- [One Monokai Theme](https://marketplace.visualstudio.com/items?itemName=azemoh.one-monokai)
- [SynthWave '84](https://marketplace.visualstudio.com/items?itemName=RobbOwen.synthwave-vscode)

Per mentioned in the Backlog:
- [Visual Studio 2019 Theme](https://marketplace.visualstudio.com/items?itemName=kast789.vs-2019-theme)
- [Monokai Dark Soda](https://marketplace.visualstudio.com/items?itemName=AdamCaviness.theme-monokai-dark-soda)
- [Darcula Theme - WebStorm Edition](https://marketplace.visualstudio.com/items?itemName=rexebin.dracula)
- [Dark Purple - WebStorm Edition](https://marketplace.visualstudio.com/items?itemName=rexebin.darkpurple)
- [Darcula Theme - Black Edition](https://marketplace.visualstudio.com/items?itemName=rexebin.dracula-black)
- [Dark Purple - Black Edition](https://marketplace.visualstudio.com/items?itemName=rexebin.darkpurple-black)
- [One Dark Pro Monokai Darker Theme](https://marketplace.visualstudio.com/items?itemName=eserozvataf.one-dark-pro-monokai-darker)

**Comment by ghaschel** [comment]
This was implemented on 2.2.1.

Feel free to reopen this issue or open a new one if there's something wrong, or even to request support for new tags or themes.

The themes were implemented in the following way:

I installed v 1.8.4, installed the themes, applied one by one and created a config file for that theme to be applied.
