### ISSUE TITLE
For some reason this extension is not working anymore in my vscode.

### ISSUE THREAD

**Issue by DanielCruz-fs** [ghaschel/vscode-angular-html#71]
This is my version of vscode:
![image](https://user-images.githubusercontent.com/29930991/198412010-418ac168-5087-4ed6-b26a-ea9f8c689514.png)
I tried everything to make it work... 
![image](https://user-images.githubusercontent.com/29930991/198412087-87df481d-9ab1-4df1-b705-56123554c6e4.png)

**Comment by ghaschel** [comment]
Did you try to run the "vscode-angular-html: Set legacy color customizations" command?

If that doesn't work, please, follow this issue bugfix template to provide me of more information about your workspace/configuration

---

Please provide the maximum amount of information in order for me to be able to fix it quicker.

Please, read the [F.A.Q.](../../docs/FAQ.md) before. Your bug might not be a bug.

**Have you read the F.A.Q.?**

- [ ] No
- [ ] Yes, but my issue has nothing to do with anything in there, or it does but something is broken.

**Describe the bug**

- A clear and concise description of what the bug is.

**List of installed/enabled extensions**
Provide a list of installed/enabled extensions. Also, try to pinpoint which extension might be conflicting with the current one if that's the case.

- Use the `code --list-extensions` command to export a list.

**OS (please provide the following information):**

- OS and Version: [e.g. Windows 10/11, Ubuntu 18.04, MacOS Catalina]
- VSCode version

**Expected behavior**

- A clear and concise description of what you expected to happen.

**Additional context**

- Add any other context about the problem here. [e.g. extension Y is not being used at its latest version, but instead, version x.y.z]

**Comment by ghaschel** [comment]
Closing as I got no response from the OP
